services:
  agent1_student:
    build: .
    container_name: agent1_student
    ports:
      - "8001:8000"
    networks:
      - ai_network
    extra_hosts:
      - "ollama:172.18.0.1"
    environment:
      - COLLECTION=agent1_student
      - NODERED_URL=http://node-red:1880
      - OLLAMA_URL=http://ollama:11434
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

networks:
  ai_network:
    external: true
