services:
  agent3_analytics:
    build: .
    container_name: agent3_analytics
    ports:
      - "8003:8000"
    networks:
      - ai_network
    environment:
      - AGENT1_URL=http://agent1_student:8001

networks:
  ai_network:
    external: true
