services:
  agent2_ticket:
    build: .
    container_name: agent2_ticket
    ports:
      - "8002:8000"
    networks:
      - ai_network
    environment:
      - COLLECTION=agent2_tickets

networks:
  ai_network:
    external: true
