services:
  agent5_security:
    build: .
    container_name: agent5_security
    ports:
      - "8005:8000"
    networks:
      - ai_network
    environment:
      - AGENT1_URL=http://agent1_student:8001

networks:
  ai_network:
    external: true
